config/routes.rb
Rails.application.routes.draw do
  root "microposts#index"  # ルートページを microposts#index に設定
  resources :microposts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  validates :content, presence: true,length: {maximum:140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  def show
    @micropost = Micropost.find(params[:id])
  end

  def index 
    @microposts = Micropost.order(updated_at: :desc) #降順で並び替える
  end

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = Micropost.new(micropost_params)
    if @micropost.save
      flash[:success] = "投稿しました"
      redirect_to root_path
    else
      if @micropost.content.length > 140
        flash[:danger] = "140文字を超えています"
      else
        flash[:danger] = "内容がありません"
      end
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    @micropost = Micropost.find(params[:id])
    if @micropost.update(micropost_params)
      flash[:success] = "更新しました"
      redirect_to root_path
    else
      if @micropost.content.length > 140
        flash[:danger] = "140文字を超えています"
      else
        flash[:danger] = "内容がありません"
      end
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to root_path, status: :see_other
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Twittery"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <!--- 何かあったら追加する --->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" style="background-color:#1e90ff;"> <!--- 直接色変更 --->
  <div class="container">
    <%= link_to "Twittery", microposts_path, id: "logo" %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <div class = "center">
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_make-micropost.html.erb
<%= form_with(model: @micropost) do |f| %>
  <h2><%= yield(:title_text)%></h2>
  <%= f.text_area :content ,placeholder: "今何してる？"%>
  <div class = "center">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<%= form_with(model: @micropost) do |f| %>
  <h2><%= yield(:title_text)%></h2>
  <%= f.text_area :content ,placeholder: "今何してる？"%>
  <div class = "text-center">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/microposts/_show-micropost.html.erb
<p><%= post.content %></p>
<div class="same-line">
  <%= link_to "詳細", micropost_path(post.id) %>
  <div class = "time">
    最終更新 <%= post.updated_at.in_time_zone("Tokyo") %> <!--- 日本時間 --->
  </div>
</div>

app/views/microposts/edit.html.erb
<% provide(:title, 'Edit Post') %>
<% provide(:button_text, 'Save Change') %>
<% provide(:title_text,'内容の編集')%>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'microposts/make-micropost' %>
  </div>
</div>

app/views/microposts/index.html.erb
<%= link_to "New Post", new_micropost_path, class: "btn btn-lg btn-primary" %>

<div class ="post-container">
  <% @microposts.each do |post| %>
    <div class = "post-row">
        <div class = "post">
          <%= render "microposts/show-micropost", post:post %>
        </div>
    </div>
  <% end %>
</div>

app/views/microposts/new.html.erb
<% provide(:title, 'New Post') %>
<% provide(:button_text, 'Create New Post') %>
<% provide(:title_text,'今何してる？')%>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'microposts/make-micropost' %>
  </div>
</div>

app/views/microposts/show.html.erb
<% provide(:title, @micropost.content) %>
<div class ="post-container">
  <div class = "post-row">
      <div class = "post">
        <%= render "microposts/show-micropost", post:@micropost %>
      </div>
  </div>
</div>

<div class = "edit-delete">
  <%= link_to "編集", edit_micropost_path(@micropost) %>
  <%= link_to "削除", @micropost, class:"delete-button",
                                  data: { "turbo-method": :delete,
                                  turbo_confirm: "このポストを削除しますか？" } %>
</div>